PROGRAM TABEL;
USES CRT;
BEGIN
     CLRSCR;
     WRITELN('зддддбдддддддддддддбддддддддддд©');
     WRITELN('Ё NO Ё     NIM     Ё   NAMA    Ё');
     WRITELN('цддддедддддддддддддеддддддддддд╢');
     WRITELN('Ё 1  Ё 3200916002  Ё   BUDI    Ё');
     WRITELN('Ё 2  Ё 3200916002  Ё   ANTOK   Ё');
     WRITELN('Ё 3  Ё 3200916003  Ё   SISKA   Ё');
     WRITELN('юддддадддддддддддддаддддддддддды');
     READLN;
END.